### PR TITLE
Move media folder - com_templates

### PR DESCRIPTION
**Pull request by astridx**
Pull Request for Issue https://github.com/joomla-projects/gsoc18_override_management/pull/62 .

### CODE REVIEW

**Comment by Anu1601CS** [comment]
@astridx Thanks for this you always make my work less :) And, Sorry, for not doing PR as i told because I am quit busy due to college work.

**Comment by astridx** [comment]
I have a problem with this PR.

I do not know, why this file is still in our master branch:  media/com_templates/css/admin-templates-default.min.css (only the min version)

This file is not in upstream anymore and I just merged upstream in our branch. 

Can someone explain why this can be?

**Comment by laoneo** [comment]
Perhaps a merge conflict.

**Comment by astridx** [comment]
If it is a merge conflict, then the same should be with the full version, right?

And in the case of  core.js and multiselect.js it is the same. Only the min versions are still on our report.  The full versions are deleted with the merge of upstream.

I think there is something special with the min-versions.

**Pull request merged**
