### PR TITLE
More changes "core" to "original"

### PR DESCRIPTION
**Pull request by richard67**
@brianteeman please review.

### CODE REVIEW

**Review by anuragteapot — APPROVED** [review]
Looks ok to me

**Comment by Anu1601CS** [comment]
@brianteeman Is this ok for you also?

**Comment by brianteeman** [comment]
yes

**Comment by richard67** [comment]
@Anu1601CS Why have you assigned this PR to me? Or was that a mistake?

**Comment by anuragteapot** [comment]
@richard67 Its not a mistake. It's your PR so its credit goes to you :)

**Comment by richard67** [comment]
Hmm, I thought "assigned" means something else. Well, merge that back to the PR in jooma_cms, then I can test later or tomorrow.

**Pull request merged**
