### PR TITLE
Move media folder - System

### PR DESCRIPTION
**Pull request by Anu1601CS**
CS and move media folder system.

### CODE REVIEW

**Comment by Anu1601CS** [comment]
> Does the core min and multiselect min files exist in upstream?

@laoneo No. But, these files exist in our repo. I don't know why ?

**Comment by laoneo** [comment]
Ok thanks

**Comment by astridx** [comment]
@zero-24 
You know a lot about Git. Much more than I. So I ask you. Do you know, why in our repo the min versions of the files we have changed in the media folder still exist? I have merged the pr at which the media folder was deleted in upstream. I can not remember a problem. Besides, the same thing should apply to the full files, right? This files are not in the our media folder any more?

Do you think it is a problem if we merge this pr here in our project. Do you mean we get a problem when we create the pr for upstream?

**Comment by zero-24** [comment]
hmm anurang is right the reason is that the file still exists in the master branch. I have just merged 4.0-dev into the master again. It seams something went wrong in this commit: https://github.com/joomla-projects/gsoc18_override_management/commit/cc607c31462c64f6e60452b9b0aa37f946bcc8a8 that added the files back. I would suggest to fix aka delete the files there in the master branch now just make sure they are exist in the correct place with the correct upstream version.

> I have merged the pr at which the media folder was deleted in upstream.

how did you dod that? Upadating this branch should be something like:

git checkout master
git remote add cms https://github.com/joomla/joomla-cms.git (only once)
git pull cms 4.0-dev
git push origin master

But you did it somehow different as you have a different commit message?

**Comment by astridx** [comment]
@zero-24 Thanks for your quick reply. 
Yes I do it with **pull** form upstream 4.0-dev and _push_ to origin master.
If I have to solve a problem, then I have to add a commit message. That is why the message sometimes different. This is correct, right?

Are you sure that the problem is in https://github.com/joomla-projects/gsoc18_override_management/commit/cc607c31462c64f6e60452b9b0aa37f946bcc8a8? Because I thought, that the media folder is deleted in this commit 4 days later:
https://github.com/joomla-projects/gsoc18_override_management/commit/3ff9601e2210fd2c9490343522498f1fc992ac62

**Comment by laoneo** [comment]
Lets get that merged. It is very likely that along the way of merging upstream something went wrong. At least now it is correct and this is good.

**Pull request merged**
